# Generated by Django 3.2 on 2022-11-22 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_collection', '0005_alter_recipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo_cloudinary',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
