# Generated by Django 3.2 on 2022-11-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_collection', '0006_recipe_photo_cloudinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo',
        ),
    ]
